name: Swift Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: blacksmith-8vcpu-ubuntu-2404-arm
    container:
      image: swift:6.2-noble

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Resolve & Test
        run: |
          rm -f Package.resolved
          swift package resolve
          swift package clean
          swift package resolve
          swift test
